export const vendorSeedData = [
  {
    ownerName: "Aarav Shah",
    businessName: "Spice Garden Hospitality",
    email: "spicegarden.owner@foodbook.app",
    phone: "9876500001",
    restaurant: {
      name: "Spice Garden",
      location: "Thaltej",
      cuisine: "Indian",
      vibe: "Fine Dining",
      rating: 4.8,
      image: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1600&q=80",
      description: "Premium multi-cuisine restaurant serving rich Indian flavors.",
    },
  },
  {
    ownerName: "Kiara Mehta",
    businessName: "Italian House Dining",
    email: "italianhouse.owner@foodbook.app",
    phone: "9876500002",
    restaurant: {
      name: "Italian House",
      location: "Sindhu Bhavan",
      cuisine: "Italian",
      vibe: "Romantic",
      rating: 4.7,
      image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1600&q=80",
      description: "Romantic Italian dining with handcrafted pasta and wood-fired pizzas.",
    },
  },
  {
    ownerName: "Dev Patel",
    businessName: "Burger Factory Foods",
    email: "burgerfactory.owner@foodbook.app",
    phone: "9876500003",
    restaurant: {
      name: "Burger Factory",
      location: "S.G. Highway",
      cuisine: "Fast Food",
      vibe: "Casual",
      rating: 4.5,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1600&q=80",
      description: "A lively casual spot for gourmet burgers and loaded sides.",
    },
  },
  {
    ownerName: "Mahi Kaur",
    businessName: "Royal Punjabi Kitchens",
    email: "royalpunjabi.owner@foodbook.app",
    phone: "9876500004",
    restaurant: {
      name: "Royal Punjabi",
      location: "Prahlad Nagar",
      cuisine: "Punjabi",
      vibe: "Family Friendly",
      rating: 4.9,
      image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1600&q=80",
      description: "Punjabi comfort food and warm family dining.",
    },
  },
  {
    ownerName: "Rohan Iyer",
    businessName: "Sushi Bloom Ventures",
    email: "sushibloom.owner@foodbook.app",
    phone: "9876500005",
    restaurant: {
      name: "Sushi Bloom",
      location: "Bodakdev",
      cuisine: "Japanese",
      vibe: "Minimal",
      rating: 4.6,
      image: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=1600&q=80",
      description: "Minimal Japanese dining with sushi, ramen, and premium plating.",
    },
  },
  {
    ownerName: "Anaya Desai",
    businessName: "Coastal Oven Group",
    email: "coastaloven.owner@foodbook.app",
    phone: "9876500006",
    restaurant: {
      name: "Coastal Oven",
      location: "Vastrapur",
      cuisine: "Seafood",
      vibe: "Luxury",
      rating: 4.8,
      image: "https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1600&q=80",
      description: "Luxury seafood dining with refined ambiance and fresh catch.",
    },
  },
  {
    ownerName: "Yash Trivedi",
    businessName: "Tandoor Terrace Collective",
    email: "tandoorterrace.owner@foodbook.app",
    phone: "9876500007",
    restaurant: {
      name: "Tandoor Terrace",
      location: "Satellite",
      cuisine: "North Indian",
      vibe: "Rooftop",
      rating: 4.7,
      image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=1600&q=80",
      description: "Open-air rooftop dining with tandoori grills, kebabs, and city views.",
    },
  },
  {
    ownerName: "Ishita Jain",
    businessName: "Green Leaf Bistro",
    email: "greenleaf.owner@foodbook.app",
    phone: "9876500008",
    restaurant: {
      name: "Green Leaf Bistro",
      location: "Navrangpura",
      cuisine: "Vegetarian",
      vibe: "Garden Cafe",
      rating: 4.4,
      image: "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1600&q=80",
      description: "Fresh vegetarian comfort food with a calm garden-style setting.",
    },
  },
  {
    ownerName: "Neel Rana",
    businessName: "Urban Curry Lab",
    email: "urbancurry.owner@foodbook.app",
    phone: "9876500009",
    restaurant: {
      name: "Urban Curry Lab",
      location: "Science City",
      cuisine: "Fusion",
      vibe: "Modern",
      rating: 4.5,
      image: "https://images.unsplash.com/photo-1515669097368-22e68427d265?auto=format&fit=crop&w=1600&q=80",
      description: "Contemporary Indian fusion with bold plating and chef-driven specials.",
    },
  },
  {
    ownerName: "Sana Sheikh",
    businessName: "Skyline BBQ House",
    email: "skylinebbq.owner@foodbook.app",
    phone: "9876500010",
    restaurant: {
      name: "Skyline BBQ House",
      location: "Gota",
      cuisine: "Barbecue",
      vibe: "Family Grill",
      rating: 4.6,
      image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1600&q=80",
      description: "Live grills, smoky platters, and hearty group dining for families and friends.",
    },
  },
];

export const restaurantSeed = vendorSeedData.map(({ restaurant }) => restaurant);
